name: Webpark
favicon: null
layout_spectrum: 0.99637
typography_spectrum: 0.6385607
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0032d2'
    - '#a5dbff'
    - '#5777e4'
    - '#29516f'
  brandStrength: 0.1691729
  lightness: 0.5430086
  saturation: 0.563063
  rhythmicContrast: 0.06486324
purpose: []
